services:
  seaweedts:
    image: seaweedts
    hostname: seaweed
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - all
    container_name: seaweedts
    restart: "no"
    command: [
      "./wait-for-it.sh", "s3:8333", "-t", "30", "--", 
      "./wait-for-it.sh", "volume:8080", "-t", "30", "--", 
      "npm", "run", "test"
    ]
    volumes:
      - ./src:/seaweed/src

  master:
    image: chrislusf/seaweedfs
    hostname: master
    container_name: master
    networks:
      - all
    restart: always
    ports:
      - 9333:9333
      - 19333:19333
    logging:
      driver: none
    command: "-v=1 master -volumeSizeLimitMB=8192 -resumeState=false -ip=master -port=9333 -peers=master:9333 -mdir=/data"

  volume:
    image: chrislusf/seaweedfs
    restart: always
    networks:
      - all
    hostname: volume
    container_name: volume
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -dataCenter=dc1 -max=1000 -rack=v1 -mserver="master:9333" -port=8080 -ip=volume -publicUrl=localhost:8080 -preStopSeconds=1'
    depends_on:
      - master
    logging:
      driver: none
    volumes:
      - volume1:/data

  filer:
    image: chrislusf/seaweedfs
    restart: always
    hostname: filer
    container_name: filer
    networks:
      - all
    ports:
      - 8888:8888
      - 18888:18888
      - 8111:8111
    command: 'filer -defaultReplicaPlacement=000 -iam -master="master:9333"'
    logging:
      driver: none
    depends_on:
      - master
      - volume

  s3:
    image: chrislusf/seaweedfs
    restart: always
    hostname: s3
    container_name: s3
    networks:
      - all
    ports:
      - 8333:8333
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -allowEmptyFolder=true -allowDeleteBucketNotEmpty=false'
    logging:
      driver: none
    depends_on:
      - master
      - volume
      - filer

  webdav:
    image: chrislusf/seaweedfs
    restart: always
    hostname: webdav
    container_name: webdav
    networks:
      - all
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    logging:
      driver: none
    depends_on:
      - master
      - volume
      - filer

networks:
  all:
    driver: bridge
    attachable: true

volumes:
  volume1:
    driver: local