name: Publish NPM Library
on:
  push: { branches: main }

jobs:
  publish:
    name: Publish NPM library
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the library
      run: npm install && npm run build

    - name: Publish the library
      run: npm run deploy
