name: Publish NPM
on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install requirements
      run: npm install

    - name: Build Library
      run: npm run build

    - name: Move README and package file to build directory
      run: cp package.json ./dist && cp README.md ./dist

    - name: Zip NPM code so it can be downloaded
      run: zip -r seaweedts ./dist/

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "seaweedts.zip"
          
  publish:
    name: Publish NPM library
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create the .npmrc file for publishing
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install requirements
      run: npm install

    - name: Build Library
      run: npm run build

    - name: Move README and package file to build directory
      run: cp package.json ./dist && cp README.md ./dist

    - name: Publish the library
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: "./dist"