name: Publish NPM Library
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the library
      run: npm install && npm run build

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "$GITHUB_REF_NAME" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} ${$GITHUB_REF_NAME#v}" \
          --generate-notes
          
  publish:
    name: Publish NPM library
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create the .npmrc file for publishing
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install requirements
      run: npm install

    - name: Build Library
      run: npm run build

    - name: Move README and package file to build directory
      run: cp package.json ./dist && cp README.md ./dist

    - name: Publish the library
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: "./dist"