name: Test suite
on:
  push:
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Build seaweed docker image
      run: docker build . --tag seaweedts

    - name: Start swarm
      run: docker swarm init

    - name: Run tests
      run: docker-compose -f seaweedfs.test.yml up --abort-on-container-exit --exit-code-from seaweedts
