name: Test suite
on:
  push:
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build seaweed testing image with cache
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: seaweedts

    - name: Start swarm
      run: docker swarm init

    - name: Run tests
      run: docker-compose -f seaweedfs.test.yml up --abort-on-container-exit --exit-code-from seaweed
